ktor:
  deployment:
    port: 8081
  application:
    modules:
      - com.example.ApplicationKt.module

database:
  driver: org.postgresql.Driver
  url: "jdbc:postgresql://gondola.proxy.rlwy.net:46744/railway"
  user: "postgres"
  password: "QZKiLKZulGXztpGLRGVvYnYpmyPorNZn"
